routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UsersController');

Route::resource('roles', 'RolController');

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\UserPermission;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function permissions()
    {
        return $this->belongsToMany('Spatie\Permission\Models\Permission', 'user_permission');
    }

    public function getPermission()
    {
        return UserPermission::where('user_id', $this->id)->get();
    }
    
}

app/UserPermission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserPermission extends Model
{
    protected $table = 'user_permission';

    protected $guarded = [];


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use App\Exceptions\AccessDeniedHttpException;
use Spatie\Permission\Models\Permission;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function checkPermission($user, $slugPermission)
    {

        $permission = null;
        $name = null;
        if (!hasPermission($user->getPermission(), $slugPermission)) {
            $permission = Permission::where('name', $slugPermission)->first();
            $name = !empty($permission) ? $permission->name : $slugPermission;
            throw new AccessDeniedHttpException(trans('responses.messages.not_permission', ['permission' => $name]));
        }
        return true;
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('home', compact('users'));
    }
}

app/Http/Controllers/RolController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;

class RolController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        
        // Checar permiso
        $this->checkPermission($user, 'roles');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Illuminate\Http\Request;
use App\User;

class UsersController extends Controller
{
    public function index()
    {

    }

    public function create()
    {
        
    }

    public function store()
    {
        
    }

    public function show()
    {
        
    }

    public function edit($id)
    {
        $user = User::find($id);

        $permission = Permission::all();

        return view('user.edit', compact('user', 'permission'));
    }

    public function update(Request $request, $id)
    {
        $user = User::find($id);

        $user->permissions()->detach();
        $permissions = $request->get('permissions', []);
       
        foreach ($permissions as $slug => $val) { 
            $permission = Permission::find($val);
            if (!empty($permission)) {
                $user->permissions()->attach($permission->id);
            }
        }

        return redirect()->route('home');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                   <table border="1">
                    <thead>
                        <th>Nombre</th>
                       <th></th>
                    </thead>
                    <tbody>
                        @foreach($users as $user)
                        <tr>
                            <td> {{$user->name}} </td>
                            <td><a href=" {{ route('user.edit', $user->id) }} " class="btn btn-primary">Edit</a></td>
                        </tr>
                        @endforeach
                    </tbody>
                   </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        @include('menu.menu')
        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/menu/menu.blade.php
@php 

    $user = Auth::user();
    $permissions = [];
    if (empty(Session::get('permissions'))) {
        Session::put('permissions', $user->getPermission());
    }
    $permissions = Session::get('permissions');

    //dd($permissions);
@endphp

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      @if (hasPermission($permissions, 'usuarios'))
        <li><a href="{{ route('user.index') }}">usuarios</a></li>
      @endif
      @if (hasPermission($permissions, 'roles'))
        <li><a href="{{ route('roles.index') }}">roles</a></li>
      @endif
      <li><a href="#">Page 3</a></li>
    </ul>
  </div>
</nav>

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    <form action=" {{route('user.update', $user->id)}} " method="POST">
                        {{ method_field('PATCH') }}
                        <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                        <input type="text" name="name"  value="{{ $user->name }}">
                        @foreach($permission as $permisso)
                            <div class="checkbox">
                                <label><input type="checkbox" value="{{ $permisso->id }}" name="permissions[]">{{ $permisso->name }}</label>
                            </div>
                        @endforeach


                        <button type="submit">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection